# This file was generated by GoReleaser. DO NOT EDIT.
cask "audit" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "777054add84f01e92e0257f46081107698f7a9cb901cbe863a72809d5418e2eb"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7d6a754ef4a0c4cb954a776a8d442f6c72fa6f7c2004a2153fee6ea71addc8a"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f0401c75db29acff45a1ee7c725a4da657cab0049ea59d2329b2d9add6f7a80"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13c425781d629fdc5aab672dc7c3b0eeed0d02bce58b91408443f3f88aff1264"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "audit"
  desc "Read-only recoverability audit for AWS and Kubernetes backups"
  homepage "https://drillproof.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drillproof"
  bash_completion "completions/drillproof.bash"
  fish_completion "completions/drillproof.fish"
  zsh_completion "completions/drillproof.zsh"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/drillproof"
    end
  end

  # No zap stanza required

end
