# This file was generated by GoReleaser. DO NOT EDIT.
cask "audit" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "ea5d328083de0957f8cb6cd80466d086be1c96c32de844bd739f9afef2b3c1c1"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a895ec041dee5ec16ee8ba63d9228a428965980852a9d0ad467cc0133ea3d6e"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88dc96c764a557369cacfdb2d151a5f3ec22c7cdc87edd94ffd5dad41af98d52"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba70bad768a258cbead2cba85d1c766431ecad260f5d756e04ed57ec3ac11541"
      url "https://github.com/drillproof/audit/releases/download/v#{version}/drillproof-audit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "audit"
  desc "Read-only recoverability audit for AWS and Kubernetes backups"
  homepage "https://drillproof.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drillproof"
  bash_completion "completions/drillproof.bash"
  fish_completion "completions/drillproof.fish"
  zsh_completion "completions/drillproof.zsh"

  postflight do
    if OS.mac?
      system "xattr", "-d", "-r", "com.apple.quarantine", "#{staged_path}/drillproof"
    end
  end

  # No zap stanza required

end
